# Generated by Django 6.0.5 on 2026-05-15 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titulo',
            new_name='Filme',
        ),
    ]
